### ISSUE TITLE
Notice: Undefined property: stdClass::$paymentResult

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#1035]
Notice: Undefined property: stdClass::$paymentResult

Seeing this logs since recently .... hope it helps

**Magento version**: 194x

**Plugin version**: 2.14.2 (but I see no code changed relevant to this in last version)

**Description**

2019-07-16T09:30:16+00:00 ERR (3): Notice: Undefined property: stdClass::$paymentResult  in app/code/community/Adyen/Payment/Model/Adyen/Abstract.php on line 512
2019-07-16T09:30:16+00:00 ERR (3): Notice: Trying to get property 'pspReference' of non-object  in app/code/community/Adyen/Payment/Model/Adyen/Abstract.php on line 512

**Comment by Aleffio** [comment]
Hi @seansan 
When do you get this error?
it seems you receive a nonempty response that is missing a pspReference,

Regards,
Alessio
Adyen

**Comment by seansan** [comment]
logs

OK maybe then a quirk ... but they exist dont know if something should be
done with it

**Comment by atty31** [comment]
I am having the same issue on 2.14.1, not sure what is causing it and how to reproduce, i didn't investigate it :(

**Comment by pbeauvais** [comment]
I've also the same issue on 2.14.2 version. After update to 2.16, the error still persist :
ERR (3): Notice: Undefined property: stdClass::$paymentResult  in /var/www/www.mondialtissus.fr/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php on line 516
ERR (3): Notice: Trying to get property of non-object  in /var/www/www.mondialtissus.fr/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php on line 516

**Comment by Mordreak** [comment]
It seems that this line remains from previous version of the file, however it is useless, I just replaced the line 56 with "$pspReference = null;" and it's working fine for now.

**Comment by Aleffio** [comment]
Hi,

You can indeed comment line 516:
`//$pspReference = $response->paymentResult->pspReference;`
or set pspReference to null.
This is indeed not used anymore since the authorisation now uses another flow.
We will apply the fix in the next version of the plugin.

Regards,
Alessio
Adyen
