### ISSUE TITLE
Firefox shows credit card number as not matching pattern

### ISSUE THREAD

**Issue by aloupfor** [Adyen/adyen-magento#935]
**Magento version**: 1
**Plugin version**: 2.11.1

**Browser**: Firefox 52.9.0

**Description**

https://github.com/Adyen/adyen-magento/blob/f1e2eea3dd37875b470cb0a7dbd4d0de7c7ee84b/app/design/frontend/base/default/template/adyen/form/cc.phtml#L46

With `pattern="[0-9]*"`, credit card number is not matching pattern as spaces are dynamically added resulting in Firefox showing a red border around the input while credit card number is valid.

Here is a screen shot of the field in cart where I duplicate the input and removed the pattern on the second one.
![screenshot from 2018-09-14 17-02-31](https://user-images.githubusercontent.com/11750180/45558404-1edcba80-b840-11e8-8f0b-252216d1d347.png)

**Comment by rikterbeek** [comment]
Hi @aloupfor,

Looks like this is a bug inside firefox. It does only provide this error it does not block transaction. But I agree this is not nice. I will change it to type="tel" and remove the pattern so this error message on Firefox is gone and the numpad is still showing on mobile devices. See fix commit above.

Regards,
Rik
Adyen

**Comment by aloupfor** [comment]
Hi @rikterbeek,

Thank you for the answer.

> Looks like this is a bug inside firefox. It does only provide this error it does not block transaction.

By "it does not block transaction", do you mean that it does not prevent the form submission?
I think that this is because spaces are also dynamically removed just before the submission.

**Comment by rikterbeek** [comment]
Hi @aloupfor,

Indeed form can be submitted. This fix should solve the error message not being shown.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @aloupfor,

This is fixed in latest release. Feel free to open a new issue if you still have issues.

Regards,
Rik
Adyen

**Comment by aloupfor** [comment]
Hi @rikterbeek,

Thank you for solving the issue.
I did not try the new release for now. As you said, I will open a new one if I still have issues.
